"""Peon application shells, CLI, TUI, and presentation policy."""

from importlib import import_module

_EXPORTS = {
	"DEFAULT_COMMAND_CATALOG": (".commands", "DEFAULT_COMMAND_CATALOG"),
	"CommandError": (".cli", "CommandError"),
	"CommandCatalog": (".commands", "CommandCatalog"),
	"CommandDefinition": (".commands", "CommandDefinition"),
	"CommandInvocation": (".commands", "CommandInvocation"),
	"CommandMatch": (".commands", "CommandMatch"),
	"CodingSession": (".coding_session", "CodingSession"),
	"Host": (".hosts", "Host"),
	"HostRole": (".hosts", "HostRole"),
	"HostUnavailableError": (".hosts", "HostUnavailableError"),
	"JsonProviderConfigStore": (".config", "JsonProviderConfigStore"),
	"JsonlTraceSink": (".observability", "JsonlTraceSink"),
	"JsonlSessionStore": (".sessions", "JsonlSessionStore"),
	"MemorySessionStore": (".sessions", "MemorySessionStore"),
	"CommandErrorOutcome": (".session_controller", "CommandErrorOutcome"),
	"CommandIntent": (".session_controller", "CommandIntent"),
	"ContinuationResponseIntent": (".session_controller", "ContinuationResponseIntent"),
	"ForkSessionIntent": (".session_controller", "ForkSessionIntent"),
	"HelpOutcome": (".session_controller", "HelpOutcome"),
	"LogoutIntent": (".session_controller", "LogoutIntent"),
	"LogoutOptionsOutcome": (".session_controller", "LogoutOptionsOutcome"),
	"LogoutSuccessOutcome": (".session_controller", "LogoutSuccessOutcome"),
	"MessageEvent": (".coding_session", "MessageEvent"),
	"ModelOption": (".session_controller", "ModelOption"),
	"ModelOptionsOutcome": (".session_controller", "ModelOptionsOutcome"),
	"ModelSelectIntent": (".session_controller", "ModelSelectIntent"),
	"NewSessionIntent": (".session_controller", "NewSessionIntent"),
	"PromptIntent": (".session_controller", "PromptIntent"),
	"ProviderSetupIntent": (".session_controller", "ProviderSetupIntent"),
	"ProviderSetupStepOutcome": (".session_controller", "ProviderSetupStepOutcome"),
	"ProviderSuccessOutcome": (".session_controller", "ProviderSuccessOutcome"),
	"ReasoningOutcome": (".session_controller", "ReasoningOutcome"),
	"ResumeOption": (".session_controller", "ResumeOption"),
	"ResumeOptionsOutcome": (".session_controller", "ResumeOptionsOutcome"),
	"ResumeSelectIntent": (".session_controller", "ResumeSelectIntent"),
	"ResumeSessionIntent": (".session_controller", "ResumeSessionIntent"),
	"SessionController": (".session_controller", "SessionController"),
	"SessionEvent": (".coding_session", "SessionEvent"),
	"SessionInfoOutcome": (".session_controller", "SessionInfoOutcome"),
	"SessionTransitionOutcome": (".session_controller", "SessionTransitionOutcome"),
	"ShellErrorOutcome": (".session_controller", "ShellErrorOutcome"),
	"ShellIntent": (".session_controller", "ShellIntent"),
	"ShellResultOutcome": (".session_controller", "ShellResultOutcome"),
	"SettingsIntent": (".session_controller", "SettingsIntent"),
	"SkillsOutcome": (".session_controller", "SkillsOutcome"),
	"ToolsOutcome": (".session_controller", "ToolsOutcome"),
	"ProviderConfig": (".cli", "ProviderConfig"),
	"ProviderConfigStore": (".config", "ProviderConfigStore"),
	"SessionRecord": (".sessions", "SessionRecord"),
	"SessionStore": (".sessions", "SessionStore"),
	"SessionStoreError": (".sessions", "SessionStoreError"),
	"TuiSession": (".tui", "TuiSession"),
	"TurnFinishedEvent": (".coding_session", "TurnFinishedEvent"),
	"TurnResult": (".coding_session", "TurnResult"),
	"TurnStartedEvent": (".coding_session", "TurnStartedEvent"),
	"UiConfig": (".config", "UiConfig"),
	"build_parser": (".cli", "build_parser"),
	"main": (".cli", "main"),
	"resolve_host": (".hosts", "resolve_host"),
	"run_tui": (".tui", "run_tui"),
}


def __getattr__(name: str) -> object:
	try:
		module_name, attribute_name = _EXPORTS[name]
	except KeyError as error:
		raise AttributeError(f"module {__name__!r} has no attribute {name!r}") from error
	value = getattr(import_module(module_name, __name__), attribute_name)
	globals()[name] = value
	return value

__all__ = [
	"DEFAULT_COMMAND_CATALOG",
	"CommandError",
	"CommandCatalog",
	"CommandDefinition",
	"CommandInvocation",
	"CommandMatch",
	"CodingSession",
	"JsonProviderConfigStore",
	"JsonlTraceSink",
	"JsonlSessionStore",
	"Host",
	"HostRole",
	"HostUnavailableError",
	"CommandErrorOutcome",
	"CommandIntent",
	"ContinuationResponseIntent",
	"ForkSessionIntent",
	"HelpOutcome",
	"LogoutIntent",
	"LogoutOptionsOutcome",
	"LogoutSuccessOutcome",
	"MemorySessionStore",
	"MessageEvent",
	"ModelOption",
	"ModelOptionsOutcome",
	"ModelSelectIntent",
	"NewSessionIntent",
	"PromptIntent",
	"ProviderSetupIntent",
	"ProviderSetupStepOutcome",
	"ProviderSuccessOutcome",
	"ReasoningOutcome",
	"ResumeOption",
	"ResumeOptionsOutcome",
	"ResumeSelectIntent",
	"ResumeSessionIntent",
	"SessionController",
	"SessionEvent",
	"SessionInfoOutcome",
	"SessionTransitionOutcome",
	"SettingsIntent",
	"ShellErrorOutcome",
	"ShellIntent",
	"ShellResultOutcome",
	"SkillsOutcome",
	"ToolsOutcome",
	"ProviderConfig",
	"ProviderConfigStore",
	"SessionRecord",
	"SessionStore",
	"SessionStoreError",
	"TuiSession",
	"TurnFinishedEvent",
	"TurnResult",
	"TurnStartedEvent",
	"UiConfig",
	"build_parser",
	"main",
	"resolve_host",
	"run_tui",
]
